# Generated by Django 2.0.4 on 2018-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180508_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default='image/users/default.png', upload_to='image/users', verbose_name='用户头像'),
        ),
    ]
