# Generated by Django 2.0.5 on 2018-05-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180508_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='verify_code',
            field=models.CharField(max_length=30, verbose_name='验证码'),
        ),
    ]
