# Generated by Django 2.0.5 on 2018-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180519_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default='media/image/users/default.png', upload_to='image/users', verbose_name='用户头像'),
        ),
    ]
