# Generated by Django 2.0.5 on 2018-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_auto_20180521_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('colleges', '高校'), ('personal', '个人'), ('orgs', '培训机构')], default='orgs', max_length=15, verbose_name='机构类别'),
        ),
    ]
