# Generated by Django 2.0.5 on 2018-05-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_auto_20180521_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='class_nums',
            field=models.IntegerField(default=0, verbose_name='课程数量'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学生数量'),
        ),
    ]
