# Generated by Django 2.0.5 on 2018-05-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0005_auto_20180523_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='class_nums',
            new_name='course_nums',
        ),
    ]
