# Generated by Django 2.0.5 on 2018-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_auto_20180523_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(default='teacher.jpeg', upload_to='image/orgs/teachers', verbose_name='教师头像'),
        ),
    ]
