# Generated by Django 2.0.5 on 2018-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0007_teacher_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(default='image/orgs/teachers/teacher.jpeg', upload_to='image/orgs/teachers', verbose_name='教师头像'),
        ),
    ]
