# Generated by Django 2.0.5 on 2018-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0009_auto_20180526_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='权威机构', max_length=8, verbose_name='机构标签'),
        ),
    ]
