# Generated by Django 2.0.5 on 2018-05-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_auto_20180523_1636'),
        ('Courses', '0003_auto_20180521_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
