# Generated by Django 2.0.5 on 2018-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=15, verbose_name='课程标签'),
        ),
    ]
