# Generated by Django 2.0.5 on 2018-06-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_vedio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vedio',
            name='video_times',
            field=models.IntegerField(default=0, verbose_name='分钟数'),
        ),
    ]
