# Generated by Django 2.0.5 on 2018-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_required',
            field=models.CharField(default='', max_length=100, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_message',
            field=models.CharField(default='', max_length=100, verbose_name='教师告诉你'),
        ),
    ]
